//该文件来放置头文件
#include "stm32f10x.h"                  // Device header
#include "OLED.h"
#include "Timer.h"
#include "Key.h"
#include "PID.h"
#include "menu.h"
#include "Delay.h"
#include "MyI2C.h"
#include "MPU6050.h"
#include "Encoder.h"
#include "PWM.h"
#include "Motor.h"
#include "Buzzer.h"
#include "infrared.h"